#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$(dirname $0)/../common/functions"

CMD=$(cat <<EOF
cd "/app" &&
new_path="\$(find / -name npm | tail -1 | xargs -I % sh -c "dirname %")" &&
PATH="\$PATH:\$new_path" &&
PATH="\$PATH:\$(npm bin)" &&
npm install -g grunt &&
npm install -g grunt-cli &&
npm install -g bower &&
npm update &&
bower --allow-root install &&
bower --allow-root update &&
EOF
)

case "$1" in
  grunt)
    [[ -z $2 ]] && echo "Please specify an app to run the command on" && exit 1
    verify_app_name "$2"
    APP="$2"
    IMAGE="dokku/$APP"
                                                                                
    if [[ -z $3 ]]; then
        echo "Usage: dokku grunt APP BUILDTYPE"
        exit 1
    fi
                                                                                
    TYPE="$3"
    # Compile with Grunt
    echo "-----> Compiling with grunt build:$TYPE"

    #id=$(docker run -d $IMAGE /bin/bash -c "$CMD")
    #docker attach $id
    #test $(docker wait $id) -eq 0
    #docker commit $id $IMAGE > /dev/null
    echo "-----> Built Grunt"
    ;;

  help)
    cat && cat<<EOF
    grunt <app> <build_type>                        Use Grunt to build
EOF
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;

esac
