#!/usr/bin/env bash
set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$(dirname $0)/../common/functions"

# Check 
if [[ $1 == grunt]] || [[ $1 == grunt:*]]; then
    if [[ -z 2 ]]; then
        echo "You must specify an app name"
        exit 1
    else
        APP=$2

        # Check if app exists with the same name
        if [! -d "$DOKKU_ROOT/$APP" ]; then
            echo "App $APP does not exist"
            exit 1
        fi
fi

case "$1" in
  grunt) # build prod or dev
    APP="$2"

    if [[ -z $3 ]]; then
        echo "Usage: dokku grunt APP BUILDTYPE"
        exit 1
    fi

    TYPE="$3"
    # Compile with Grunt
    echo "-----> Compiling with grunt build:$TYPE"
    grunt build:$TYPE
    bind_restart_app $APP
    ;;

  help)
    cat && cat<<EOF
    grunt <app> <build_type>                        Use Grunt to build (grunt build:<build_type>
EOF
    ;;

  *)
    exit $DOKKU_NOT_IMPLEMENTED_EXIT
    ;;
esac
